;___________________________________________
; Invincible by Xtry
; Events
; mailto: InvincibleScript@yahoo.com
;¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯

on *:INPUT:?:{
  if ($group(#gtzcoltxt) = on) && (%coltalk.x = on) { halt }
  if (/ !isin $left($1,1)) {
    if ($group(#scsc) = on) && ($1 = $read(utilities\emo\st.txt,w,$1)) {
      if ($1 = hahaha) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lha2.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = hihihi) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhi2.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = hehehe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhe2.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = huhuhu) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhu2.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = hohoho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lho2.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = haha) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lha.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = hihi) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhi.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = hehe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhe.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = huhu) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhu.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = hoho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lho.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = lol) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ut  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ oud $+ $color(own) $2- | halt }
      if ($1 = $chr(59) $+ $chr(41)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smile.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(59) $+ $chr(40)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/badf.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(59) $+ $chr(124)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(58) $+ $chr(41)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smile.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(58) $+ $chr(40)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/badf.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(58) $+ $chr(124)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = ?) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/qh.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(59) $+ o) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/shf.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(59) $+ p) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/wekx.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(59) $+ d) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smileb.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(59) $+ x) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/upsups.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(59) $+ \) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap3.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(59) $+ /) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap2.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(58) $+ o) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/shf.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(58) $+ p) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/wekx.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(58) $+ d) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smileb.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(58) $+ x) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/upsups.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(58) $+ \) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap3.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = $chr(58) $+ /) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap2.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = !) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/shoxxx.txt) $+  $+ $color(own) $2- | halt }
      if ($1 = wb) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ elcome  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack $+ $color(own) $2- | halt }
      if ($1 = tyt) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ake  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ our  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime $+ $color(own) $2- | halt }
      if ($1 = np) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ P $+ $cgtz(2) $+ roblem $+ $color(own) $2- | halt }
      if ($1 = yw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ elcome $+ $color(own) $2- | halt }
      if ($1 = brb) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ ight  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack $+ $color(own) $2- | halt }
      if ($1 = bbl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ater $+ $color(own) $2- | halt }
      if ($1 = bbs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ oon $+ $color(own) $2- | halt }
      if ($1 = tc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ake  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ are $+ $color(own) $2- | halt }
      if ($1 = omg) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ h  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ od $+ $color(own) $2- | halt }
      if ($1 = ok) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ k $+ $color(own) $2- | halt }
      if ($1 = okay) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ kay $+ $color(own) $2- | halt }
      if ($1 = k) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ k $+ $color(own) $2- | halt }
      if ($1 = yes) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ es $+ $color(own) $2- | halt }
      if ($1 = yup) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ up $+ $color(own) $2- | halt }
      if ($1 = yep) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ep $+ $color(own) $2- | halt }
      if ($1 = yupe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ upe $+ $color(own) $2- | halt }
      if ($1 = no) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o $+ $color(own) $2- | halt }
      if ($1 = nope) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ ope $+ $color(own) $2- | halt }
      if ($1 = nop) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ op $+ $color(own) $2- | halt }
      if ($1 = ty) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hank  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou $+ $color(own) $2- | halt }
      if ($1 = gtg) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ ot  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ o $+ $color(own) $2- | halt }
      if ($1 = asl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ge  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ex  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ocation $+ $color(own) $2- | halt }
      if ($1 = gts) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ ot  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ leep $+ $color(own) $2- | halt }
      if ($1 = nbd) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ig  $+ $cgtz(1) $+ D $+ $cgtz(2) $+ eals $+ $color(own) $2- | halt }
      if ($1 = jk) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ idding $+ $color(own) $2- | halt }
      if ($1 = j/k) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ idding $+ $color(own) $2- | halt }
      if ($1 = pls) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ P $+ $cgtz(2) $+ lease $+ $color(own) $2- | halt }
      if ($1 = ic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ I $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
      if ($1 = btw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ay $+ $color(own) $2- | halt }
      if ($1 = imho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ onest  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ pinion $+ $color(own) $2- | halt }
      if ($1 = ltns) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ong  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
      if ($1 = ltnc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ong  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
      if ($1 = oic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ h  $+ $cgtz(1) $+ I $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
      if ($1 = thx) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hanks $+ $color(own) $2- | halt }
      if ($1 = tnx) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hanks $+ $color(own) $2- | halt }
      if ($1 = ctc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ are  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ hat $+ $color(own) $2- | halt }
      if ($1 = wtf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ hat  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
      if ($1 = gtf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ et  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
      if ($1 = gth) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ ell $+ $color(own) $2- | halt }
      if ($1 = jic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ ase $+ $color(own) $2- | halt }
      if ($1 = wth) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ hat  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ ell $+ $color(own) $2- | halt }
      if ($1 = bye) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ye  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ye $+ $color(own) $2- | halt }
      if ($1 = nm) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ evermind $+ $color(own) $2- | halt }
      if ($1 = nvm) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ evermind $+ $color(own) $2- | halt }
      if ($1 = cool) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ ool $+ $color(own) $2- | halt }
      if ($1 = kewl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ ewl $+ $color(own) $2- | halt }
      if ($1 = ttyl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ alk  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ater $+ $color(own) $2- | halt }
      if ($1 = bbiaf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ A F $+ $cgtz(2) $+ ew $+ $color(own) $2- | halt }
      if ($1 = rofl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing $+ $color(own) $2- | halt }
      if ($1 = rotfl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing $+ $color(own) $2- | halt }
      if ($1 = rotflmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
      if ($1 = roflmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
      if ($1 = bs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ull  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ hit $+ $color(own) $2- | halt }
      if ($1 = hs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ oly  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ hit $+ $color(own) $2- | halt }
      if ($1 = ys) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
      if ($1 = wd) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ell  $+ $cgtz(1) $+ D $+ $cgtz(2) $+ one $+ $color(own) $2- | halt }
      if ($1 = nw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ay $+ $color(own) $2- | halt }
      if ($1 = cya) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ a $+ $color(own) $2- | halt }
      if ($1 = heh) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ eh $+ $color(own) $2- | halt }
      if ($1 = afk) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ way  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ rom  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ eyboard $+ $color(own) $2- | halt }
      if ($1 = lmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
    }
    else {
      echo -at  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $1-
      .msg $active $1-
      haltdef
    }
  }
}

on *:INPUT:#:{
  if ($right($1,1) isin $remove(%xtncpro-ativa,$chr(32))) && (%xtncpro-on) { halt }
  if ($group(#gtzcoltxt) = on) && (%coltalk.x = on) { halt }
  if ($left($1,3) = /me) && ($left($1,9) != /memoserv) {
    if ($me isop $chan) && ($me !isvo $chan) && ($me !isreg $chan) { .me $2- | echo -t $chan  $+ $color(action) $+ @ $+ $me $2- | haltdef }
    if ($me isvo $chan) && ($me !isop $chan) && ($me !isreg $chan) { .me $2- | echo -t $chan  $+ $color(action) $+ + $+ $me $2- | haltdef }
    if ($me isreg $chan) && ($me !isop $chan) && ($me !isvo $chan) { .me $2- | echo -t $chan  $+ $color(action) $+ $me $2- | haltdef }
  }
  if (/ !isin $left($1,1)) && ($me ison $chan) {
    if ($me isop $chan) {
      if ($group(#scsc) = on) && ($1 = $read(utilities\emo\st.txt,w,$1)) {
        if ($1 = hahaha) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/lha2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hihihi) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhi2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hehehe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhe2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = huhuhu) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhu2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hohoho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/lho2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = haha) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/lha.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hihi) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhi.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hehe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhe.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = huhu) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhu.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hoho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/lho.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = lol) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ut  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ oud $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ $chr(41)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smile.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ $chr(40)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/badf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ $chr(124)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ $chr(41)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smile.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ $chr(40)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/badf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ $chr(124)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = ?) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/qh.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ o) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/shf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ p) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/wekx.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ d) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smileb.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ x) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/upsups.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ \) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap3.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ /) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ o) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/shf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ p) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/wekx.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ d) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smileb.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ x) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/upsups.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ \) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap3.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ /) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = !) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ : $read(utilities/emo/shoxxx.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = wb) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ elcome  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack $+ $color(own) $2- | halt }
        if ($1 = tyt) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ake  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ our  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime $+ $color(own) $2- | halt }
        if ($1 = np) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ P $+ $cgtz(2) $+ roblem $+ $color(own) $2- | halt }
        if ($1 = yw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ elcome $+ $color(own) $2- | halt }
        if ($1 = brb) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ ight  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack $+ $color(own) $2- | halt }
        if ($1 = bbl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ater $+ $color(own) $2- | halt }
        if ($1 = bbs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ oon $+ $color(own) $2- | halt }
        if ($1 = tc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ake  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ are $+ $color(own) $2- | halt }
        if ($1 = omg) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ h  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ od $+ $color(own) $2- | halt }
        if ($1 = ok) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ k $+ $color(own) $2- | halt }
        if ($1 = okay) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ kay $+ $color(own) $2- | halt }
        if ($1 = k) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ k $+ $color(own) $2- | halt }
        if ($1 = yes) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ es $+ $color(own) $2- | halt }
        if ($1 = yup) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ up $+ $color(own) $2- | halt }
        if ($1 = yep) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ep $+ $color(own) $2- | halt }
        if ($1 = yupe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ upe $+ $color(own) $2- | halt }
        if ($1 = no) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o $+ $color(own) $2- | halt }
        if ($1 = nope) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ ope $+ $color(own) $2- | halt }
        if ($1 = nop) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ op $+ $color(own) $2- | halt }
        if ($1 = ty) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hank  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou $+ $color(own) $2- | halt }
        if ($1 = gtg) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ ot  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ o $+ $color(own) $2- | halt }
        if ($1 = asl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ge  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ex  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ocation $+ $color(own) $2- | halt }
        if ($1 = gts) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ ot  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ leep $+ $color(own) $2- | halt }
        if ($1 = nbd) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ig  $+ $cgtz(1) $+ D $+ $cgtz(2) $+ eals $+ $color(own) $2- | halt }
        if ($1 = jk) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ idding $+ $color(own) $2- | halt }
        if ($1 = j/k) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ idding $+ $color(own) $2- | halt }
        if ($1 = pls) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ P $+ $cgtz(2) $+ lease $+ $color(own) $2- | halt }
        if ($1 = ic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ I $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = btw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ay $+ $color(own) $2- | halt }
        if ($1 = imho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ onest  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ pinion $+ $color(own) $2- | halt }
        if ($1 = ltns) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ong  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = ltnc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ong  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = oic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ h  $+ $cgtz(1) $+ I $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = thx) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hanks $+ $color(own) $2- | halt }
        if ($1 = tnx) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hanks $+ $color(own) $2- | halt }
        if ($1 = ctc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ are  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ hat $+ $color(own) $2- | halt }
        if ($1 = wtf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ hat  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
        if ($1 = gtf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ et  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
        if ($1 = gth) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ ell $+ $color(own) $2- | halt }
        if ($1 = jic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ ase $+ $color(own) $2- | halt }
        if ($1 = wth) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ hat  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ ell $+ $color(own) $2- | halt }
        if ($1 = bye) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ye  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ye $+ $color(own) $2- | halt }
        if ($1 = nm) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ evermind $+ $color(own) $2- | halt }
        if ($1 = nvm) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ evermind $+ $color(own) $2- | halt }
        if ($1 = cool) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ ool $+ $color(own) $2- | halt }
        if ($1 = kewl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ ewl $+ $color(own) $2- | halt }
        if ($1 = ttyl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ alk  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ater $+ $color(own) $2- | halt }
        if ($1 = bbiaf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ A F $+ $cgtz(2) $+ ew $+ $color(own) $2- | halt }
        if ($1 = rofl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing $+ $color(own) $2- | halt }
        if ($1 = rotfl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing $+ $color(own) $2- | halt }
        if ($1 = rotflmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
        if ($1 = roflmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
        if ($1 = bs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ull  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ hit $+ $color(own) $2- | halt }
        if ($1 = hs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ oly  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ hit $+ $color(own) $2- | halt }
        if ($1 = ys) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
        if ($1 = wd) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ell  $+ $cgtz(1) $+ D $+ $cgtz(2) $+ one $+ $color(own) $2- | halt }
        if ($1 = nw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ay $+ $color(own) $2- | halt }
        if ($1 = cya) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ a $+ $color(own) $2- | halt }
        if ($1 = heh) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ eh $+ $color(own) $2- | halt }
        if ($1 = afk) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ way  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ rom  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ eyboard $+ $color(own) $2- | halt }
        if ($1 = lmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ @ $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
      }
      else {
        _xmsg.c $1-
        haltdef
      }
    }
    if ($me isvo $chan) && ($me !isop $chan) && ($me !isreg $chan) {
      if ($group(#scsc) = on) && ($1 = $read(utilities\emo\st.txt,w,$1)) {
        if ($1 = hahaha) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/lha2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hihihi) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhi2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hehehe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhe2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = huhuhu) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhu2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hohoho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/lho2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = haha) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/lha.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hihi) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhi.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hehe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhe.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = huhu) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhu.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hoho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/lho.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = lol) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ut  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ oud $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ $chr(41)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smile.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ $chr(40)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/badf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ $chr(124)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ $chr(41)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smile.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ $chr(40)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/badf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ $chr(124)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = ?) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/qh.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ o) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/shf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ p) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/wekx.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ d) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smileb.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ x) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/upsups.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ \) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap3.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ /) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ o) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/shf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ p) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/wekx.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ d) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smileb.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ x) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/upsups.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ \) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap3.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ /) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = !) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ : $read(utilities/emo/shoxxx.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = wb) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ elcome  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack $+ $color(own) $2- | halt }
        if ($1 = tyt) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ake  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ our  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime $+ $color(own) $2- | halt }
        if ($1 = np) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ P $+ $cgtz(2) $+ roblem $+ $color(own) $2- | halt }
        if ($1 = yw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ elcome $+ $color(own) $2- | halt }
        if ($1 = brb) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ ight  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack $+ $color(own) $2- | halt }
        if ($1 = bbl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ater $+ $color(own) $2- | halt }
        if ($1 = bbs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ oon $+ $color(own) $2- | halt }
        if ($1 = tc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ake  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ are $+ $color(own) $2- | halt }
        if ($1 = omg) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ h  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ od $+ $color(own) $2- | halt }
        if ($1 = ok) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ k $+ $color(own) $2- | halt }
        if ($1 = okay) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ kay $+ $color(own) $2- | halt }
        if ($1 = k) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ k $+ $color(own) $2- | halt }
        if ($1 = yes) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ es $+ $color(own) $2- | halt }
        if ($1 = yup) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ up $+ $color(own) $2- | halt }
        if ($1 = yep) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ep $+ $color(own) $2- | halt }
        if ($1 = yupe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ upe $+ $color(own) $2- | halt }
        if ($1 = no) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o $+ $color(own) $2- | halt }
        if ($1 = nope) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ ope $+ $color(own) $2- | halt }
        if ($1 = nop) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ op $+ $color(own) $2- | halt }
        if ($1 = ty) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hank  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou $+ $color(own) $2- | halt }
        if ($1 = gtg) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ ot  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ o $+ $color(own) $2- | halt }
        if ($1 = asl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ge  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ex  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ocation $+ $color(own) $2- | halt }
        if ($1 = gts) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ ot  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ leep $+ $color(own) $2- | halt }
        if ($1 = nbd) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ig  $+ $cgtz(1) $+ D $+ $cgtz(2) $+ eals $+ $color(own) $2- | halt }
        if ($1 = jk) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ idding $+ $color(own) $2- | halt }
        if ($1 = j/k) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ idding $+ $color(own) $2- | halt }
        if ($1 = pls) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ P $+ $cgtz(2) $+ lease $+ $color(own) $2- | halt }
        if ($1 = ic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ I $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = btw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ay $+ $color(own) $2- | halt }
        if ($1 = imho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ onest  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ pinion $+ $color(own) $2- | halt }
        if ($1 = ltns) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ong  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = ltnc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ong  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = oic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ h  $+ $cgtz(1) $+ I $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = thx) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hanks $+ $color(own) $2- | halt }
        if ($1 = tnx) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hanks $+ $color(own) $2- | halt }
        if ($1 = ctc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ are  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ hat $+ $color(own) $2- | halt }
        if ($1 = wtf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ hat  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
        if ($1 = gtf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ et  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
        if ($1 = gth) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ ell $+ $color(own) $2- | halt }
        if ($1 = jic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ ase $+ $color(own) $2- | halt }
        if ($1 = wth) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ hat  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ ell $+ $color(own) $2- | halt }
        if ($1 = bye) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ye  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ye $+ $color(own) $2- | halt }
        if ($1 = nm) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ evermind $+ $color(own) $2- | halt }
        if ($1 = nvm) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ evermind $+ $color(own) $2- | halt }
        if ($1 = cool) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ ool $+ $color(own) $2- | halt }
        if ($1 = kewl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ ewl $+ $color(own) $2- | halt }
        if ($1 = ttyl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ alk  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ater $+ $color(own) $2- | halt }
        if ($1 = bbiaf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ A F $+ $cgtz(2) $+ ew $+ $color(own) $2- | halt }
        if ($1 = rofl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing $+ $color(own) $2- | halt }
        if ($1 = rotfl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing $+ $color(own) $2- | halt }
        if ($1 = rotflmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
        if ($1 = roflmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
        if ($1 = bs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ull  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ hit $+ $color(own) $2- | halt }
        if ($1 = hs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ oly  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ hit $+ $color(own) $2- | halt }
        if ($1 = ys) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
        if ($1 = wd) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ell  $+ $cgtz(1) $+ D $+ $cgtz(2) $+ one $+ $color(own) $2- | halt }
        if ($1 = nw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ay $+ $color(own) $2- | halt }
        if ($1 = cya) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ a $+ $color(own) $2- | halt }
        if ($1 = heh) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ eh $+ $color(own) $2- | halt }
        if ($1 = afk) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ way  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ rom  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ eyboard $+ $color(own) $2- | halt }
        if ($1 = lmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ + $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
      }
      else {
        _xmsg.c $1-
        haltdef
      }
    }
    if ($me isreg $chan) && ($me !isop $chan) && ($me !isvo $chan) {
      if ($group(#scsc) = on) && ($1 = $read(utilities\emo\st.txt,w,$1)) {
        if ($1 = hahaha) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lha2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hihihi) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhi2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hehehe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhe2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = huhuhu) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhu2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hohoho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lho2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = haha) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lha.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hihi) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhi.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hehe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhe.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = huhu) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lhu.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = hoho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/lho.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = lol) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ut  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ oud $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ $chr(41)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smile.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ $chr(40)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/badf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ $chr(124)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ $chr(41)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smile.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ $chr(40)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/badf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ $chr(124)) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = ?) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/qh.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ o) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/shf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ p) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/wekx.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ d) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smileb.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ x) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/upsups.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ \) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap3.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(59) $+ /) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ o) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/shf.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ p) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/wekx.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ d) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/smileb.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ x) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/upsups.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ \) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap3.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = $chr(58) $+ /) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $read(utilities/emo/disap2.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = !) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ : $read(utilities/emo/shoxxx.txt) $+  $+ $color(own) $2- | halt }
        if ($1 = wb) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ elcome  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack $+ $color(own) $2- | halt }
        if ($1 = tyt) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ake  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ our  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime $+ $color(own) $2- | halt }
        if ($1 = np) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ P $+ $cgtz(2) $+ roblem $+ $color(own) $2- | halt }
        if ($1 = yw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ elcome $+ $color(own) $2- | halt }
        if ($1 = brb) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ ight  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack $+ $color(own) $2- | halt }
        if ($1 = bbl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ater $+ $color(own) $2- | halt }
        if ($1 = bbs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ oon $+ $color(own) $2- | halt }
        if ($1 = tc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ake  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ are $+ $color(own) $2- | halt }
        if ($1 = omg) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ h  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ od $+ $color(own) $2- | halt }
        if ($1 = ok) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ k $+ $color(own) $2- | halt }
        if ($1 = okay) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ kay $+ $color(own) $2- | halt }
        if ($1 = k) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ k $+ $color(own) $2- | halt }
        if ($1 = yes) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ es $+ $color(own) $2- | halt }
        if ($1 = yup) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ up $+ $color(own) $2- | halt }
        if ($1 = yep) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ep $+ $color(own) $2- | halt }
        if ($1 = yupe) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ upe $+ $color(own) $2- | halt }
        if ($1 = no) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o $+ $color(own) $2- | halt }
        if ($1 = nope) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ ope $+ $color(own) $2- | halt }
        if ($1 = nop) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ op $+ $color(own) $2- | halt }
        if ($1 = ty) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hank  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou $+ $color(own) $2- | halt }
        if ($1 = gtg) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ ot  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ o $+ $color(own) $2- | halt }
        if ($1 = asl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ge  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ex  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ocation $+ $color(own) $2- | halt }
        if ($1 = gts) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ ot  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ leep $+ $color(own) $2- | halt }
        if ($1 = nbd) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ig  $+ $cgtz(1) $+ D $+ $cgtz(2) $+ eals $+ $color(own) $2- | halt }
        if ($1 = jk) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ idding $+ $color(own) $2- | halt }
        if ($1 = j/k) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ idding $+ $color(own) $2- | halt }
        if ($1 = pls) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ P $+ $cgtz(2) $+ lease $+ $color(own) $2- | halt }
        if ($1 = ic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ I $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = btw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ay $+ $color(own) $2- | halt }
        if ($1 = imho) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ onest  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ pinion $+ $color(own) $2- | halt }
        if ($1 = ltns) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ong  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = ltnc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ong  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ ime  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = oic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ h  $+ $cgtz(1) $+ I $cgtz(1) $+ S $+ $cgtz(2) $+ ee $+ $color(own) $2- | halt }
        if ($1 = thx) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hanks $+ $color(own) $2- | halt }
        if ($1 = tnx) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ hanks $+ $color(own) $2- | halt }
        if ($1 = ctc) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ are  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ hat $+ $color(own) $2- | halt }
        if ($1 = wtf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ hat  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
        if ($1 = gtf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ et  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
        if ($1 = gth) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ G $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ ell $+ $color(own) $2- | halt }
        if ($1 = jic) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ J $+ $cgtz(2) $+ ust  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ ase $+ $color(own) $2- | halt }
        if ($1 = wth) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ hat  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ ell $+ $color(own) $2- | halt }
        if ($1 = bye) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ye  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ye $+ $color(own) $2- | halt }
        if ($1 = nm) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ evermind $+ $color(own) $2- | halt }
        if ($1 = nvm) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ evermind $+ $color(own) $2- | halt }
        if ($1 = cool) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ C $+ $cgtz(2) $+ ool $+ $color(own) $2- | halt }
        if ($1 = kewl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ ewl $+ $color(own) $2- | halt }
        if ($1 = ttyl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ alk  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ ater $+ $color(own) $2- | halt }
        if ($1 = bbiaf) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ e  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ack  $+ $cgtz(1) $+ I $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ A F $+ $cgtz(2) $+ ew $+ $color(own) $2- | halt }
        if ($1 = rofl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing $+ $color(own) $2- | halt }
        if ($1 = rotfl) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing $+ $color(own) $2- | halt }
        if ($1 = rotflmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
        if ($1 = roflmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ R $+ $cgtz(2) $+ olling  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ n  $+ $cgtz(1) $+ T $+ $cgtz(2) $+ he  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ loor  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
        if ($1 = bs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ B $+ $cgtz(2) $+ ull  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ hit $+ $color(own) $2- | halt }
        if ($1 = hs) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ oly  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ hit $+ $color(own) $2- | halt }
        if ($1 = ys) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ ou  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ uck $+ $color(own) $2- | halt }
        if ($1 = wd) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ell  $+ $cgtz(1) $+ D $+ $cgtz(2) $+ one $+ $color(own) $2- | halt }
        if ($1 = nw) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ N $+ $cgtz(2) $+ o  $+ $cgtz(1) $+ W $+ $cgtz(2) $+ ay $+ $color(own) $2- | halt }
        if ($1 = cya) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ S $+ $cgtz(2) $+ ee  $+ $cgtz(1) $+ Y $+ $cgtz(2) $+ a $+ $color(own) $2- | halt }
        if ($1 = heh) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ H $+ $cgtz(2) $+ eh $+ $color(own) $2- | halt }
        if ($1 = afk) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ way  $+ $cgtz(1) $+ F $+ $cgtz(2) $+ rom  $+ $cgtz(1) $+ K $+ $cgtz(2) $+ eyboard $+ $color(own) $2- | halt }
        if ($1 = lmao) && ($left($1-,1) != /) && ($left($1-,1) != .) { echo -t $chan  $+ $_nc.rini(nc,m-) $+ $me  $+ $color(own) $+ :  $+ $cgtz(1) $+ L $+ $cgtz(2) $+ aughing  $+ $cgtz(1) $+ M $+ $cgtz(2) $+ y  $+ $cgtz(1) $+ A $+ $cgtz(2) $+ ss  $+ $cgtz(1) $+ O $+ $cgtz(2) $+ ff $+ $color(own) $2- | halt }
      }
      else {
        _xmsg.c $1-
        haltdef
      }
    }
  }
}

;___________________________________________________________________________
; Copyright © 2000 - 2003 logos,scripts & codes. All rights reserved
; Reproduction/distribution/alteration of this material in part or in full without prior consent is forbidden
; Script author: Xtry on dalnet.
; mailto: InvincibleScript@yahoo.com
;¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
